name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'  # Usa la versión de Flutter que necesitas

    - name: Disable Flutter analytics
      run: flutter config --no-analytics  # Comando para desactivar los analytics

    - name: Install dependencies
      run: flutter pub get  # Instala las dependencias

    - name: Build APK
      run: flutter build apk --release  # Compila el APK
