name: Build Flutter APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'

    - name: Change directory to the project folder
      run: cd Pokemon  # Cambia a la carpeta donde está tu archivo pubspec.yaml

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release


